"""empty message

Revision ID: 341ca618494b
Revises: 46cfdef059f1
Create Date: 2020-06-05 16:01:29.244323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341ca618494b'
down_revision = '46cfdef059f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
